services:
  geoparsing-notebook:
    image: dguzh/cas-geoparsing:latest
    container_name: geoparsing-notebook
    ports:
      - "8888:8888"
    volumes:
      # Save your work locally
      - ./notebooks:/workspace
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped

